server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    password: mypassword
    username: myuser
  data:
    mongodb:
      host: localhost
      port: 27017
      database: analytics
      username: appUser
      password: password
